---
- name: Install GitLab dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ gitlab_apt_dependencies }}"

- name: Run script to check system and add repository for GitLab CE
  shell: "curl -L {{ gitlab_script_url }} | bash"
  when:
    - gitlab_script_url is defined
