---
- block:
  - name: Install GitLab dependencies
    yum:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - "{{ gitlab_yum_dependencies }}"
    notify:
      - Start sshd
      - Start postfix

  - name: Enable firewalld
    firewalld:
      service: "{{ item.1 }}"
      permanent: true
      state: enabled
      immediate: yes
    with_indexed_items:
      - http
  when: ansible_os_family == "RedHat"

- name: Install GitLab dependencies
  apt:
    name: "{{ gitlab_apt_package }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debain"

- name: Run script to check system and add repository for GitLab CE
  shell: "curl -L -s {{ gitlab_script_url }} | bash"
  when:
    - gitlab_script_url is defined
