---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include: gitlab_pre.yml
- include: gitlab_install.yml

- block: # Config GitLab
  - include: gitlab_search_config.yml
  - include: gitlab_post.yml
  tags:
    - gitlab-config
